### ISSUE TITLE
v1.0.2 won't install on android 13

### ISSUE THREAD

**Issue by joeyiii57** [EnixCoda/SMS-Forward#11]
v1.0.2 wont install.  Installer says "invalid package".  v1.0.1 installs and works fine.

**Comment by EnixCoda** [comment]
Thanks for letting me know. I do not have Android device anymore so that I could not have tested the APK.

The 1.0.2 is built on my new machine and there seems to be some build problems that its size is times larger than 1.0.1 while there is almost no source code change.

Will try to figure out later. And if anyone familiar with Android development could help, I'll appreciate that!

**Comment by EnixCoda** [comment]
Hi @joeyiii57 

I've updated build config and re-uploaded the APK.

https://github.com/EnixCoda/SMS-Forward/releases/tag/1.0.2

It is compiled against API 34 (higher than Android 13), hope it works this time.

**Comment by joeyiii57** [comment]
> Hi @joeyiii57
> 
> I've updated build config and re-uploaded the APK.
> 
> https://github.com/EnixCoda/SMS-Forward/releases/tag/1.0.2
> 
> It is compiled against API 34 (higher than Android 13), hope it works this time.

Seems to work perfectly, thanks...
